OutputPath: '{filepath}{PathSeparator}'
OutputFilename: '{now:yyyyMMddHHmmss}_{filenamebase}.pdf'
OverwriteOutputWhenExist: true
DefaultFormats:
  DateTimeFormat: yyyy-MM-dd HH.mm.ss
  DateFormat: yyyy-MM-dd
  TimeFormat: HH.mm.ss
DocVariables:
  Now: '{Now}'
  Time: '{Time}'
  Date: '{Date}'
  FilenameBase: '{FilenameBase}'
  Filename: '{Filename}'
  FilePath: '{FilePath}'
  FileExtension: '{FileExtension}'
  PathSeparator: '{PathSeparator}'
  empty: '{empty}'
  Env.Os: '{Env.Os}'
  Env.ComputerName: '{Env.ComputerName}'
  Git.Sha: '{Git.Sha}'
  Git.Message: '{Git.Message}'
  Git.MessageShort: '{Git.MessageShort}'
  Git.Author.Email: '{Git.Author.Email}'
  Git.Author.Name: '{Git.Author.Name}'
  Git.Author.CommitDate: '{Git.Author.CommitDate}'
  Git.Committer.Email: '{Git.Committer.Email}'
  Git.Committer.Name: '{Git.Committer.Name}'
  Git.Committer.CommitDate: '{Git.Committer.CommitDate}'
  Git.RootDir: '{Git.RootDir}'
  GitVersion.CommitDate: '{GitVersion.CommitDate}'
  GitVersion.AssemblySemFileVer: '{GitVersion.AssemblySemFileVer}'
  GitVersion.AssemblySemVer: '{GitVersion.AssemblySemVer}'
  GitVersion.BranchName: '{GitVersion.BranchName}'
  GitVersion.BuildMetaData: '{GitVersion.BuildMetaData}'
  GitVersion.BuildMetaDataPadded: '{GitVersion.BuildMetaDataPadded}'
  GitVersion.CommitsSinceVersionSource: '{GitVersion.CommitsSinceVersionSource}'
  GitVersion.CommitsSinceVersionSourcePadded: '{GitVersion.CommitsSinceVersionSourcePadded}'
  GitVersion.EscapedBranchName: '{GitVersion.EscapedBranchName}'
  GitVersion.FullBuildMetaData: '{GitVersion.FullBuildMetaData}'
  GitVersion.FullSemVer: '{GitVersion.FullSemVer}'
  GitVersion.InformationalVersion: '{GitVersion.InformationalVersion}'
  GitVersion.LegacySemVer: '{GitVersion.LegacySemVer}'
  GitVersion.LegacySemVerPadded: '{GitVersion.LegacySemVerPadded}'
  GitVersion.Major: '{GitVersion.Major}'
  GitVersion.MajorMinorPatch: '{GitVersion.MajorMinorPatch}'
  GitVersion.Minor: '{GitVersion.Minor}'
  GitVersion.NuGetPreReleaseTag: '{GitVersion.NuGetPreReleaseTag}'
  GitVersion.NuGetPreReleaseTagV2: '{GitVersion.NuGetPreReleaseTagV2}'
  GitVersion.NuGetVersion: '{GitVersion.NuGetVersion}'
  GitVersion.NuGetVersionV2: '{GitVersion.NuGetVersionV2}'
  GitVersion.Patch: '{GitVersion.Patch}'
  GitVersion.PreReleaseLabel: '{GitVersion.PreReleaseLabel}'
  GitVersion.PreReleaseNumber: '{GitVersion.PreReleaseNumber}'
  GitVersion.PreReleaseTag: '{GitVersion.PreReleaseTag}'
  GitVersion.PreReleaseTagWithDash: '{GitVersion.PreReleaseTagWithDash}'
  GitVersion.SemVer: '{GitVersion.SemVer}'
  GitVersion.Sha: '{GitVersion.Sha}'
  GitVersion.ShortSha: '{GitVersion.ShortSha}'
  GitVersion.VersionSourceSha: '{GitVersion.VersionSourceSha}'
  GitVersion.WeightedPreReleaseNumber: '{GitVersion.WeightedPreReleaseNumber}'
  CustomVersionInfo: 'Version: {GitVersion.FullSemVer} committed on {Git.Author.CommitDate:yyyyMMdd} by {Git.Author.Name}.'
  CustomRenderDate: 'Copyright 2010-{now:yyyy}.'
  Host: '{Host}'
  GithubUrl: 'https://github.com/coenm/VersionedPdfGenerator/commit/{Git.Sha}'
  GithubUrlEncoded: '{UrlEncode(https://github.com/coenm/VersionedPdfGenerator/commit/{Git.Sha})}'